# Generated by Django 4.1.7 on 2023-08-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_content_event_content_pastevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_project_m',
            field=models.FileField(upload_to='media/event/'),
        ),
    ]
