# Generated by Django 4.1.7 on 2023-05-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='videos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
