version: "3"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: FabLab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
