# Generated by Django 4.1.7 on 2023-06-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectMakandura', '0006_projectmakandura_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmakandura',
            name='image_project_m',
            field=models.FileField(null=True, upload_to='media/news/'),
        ),
    ]
