# Generated by Django 4.1.7 on 2023-08-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectMakandura', '0007_alter_projectmakandura_image_project_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmakandura',
            name='image_project_m',
            field=models.TextField(),
        ),
    ]
